apiVersion: v1
kind: Pod
metadata:
  name: break-etcd
  namespace: default
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - name: debug
    image: quay.io/quay/busybox
    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting before disrupting etcd..."
        sleep 10
        echo "Looking for etcd container..."
        chroot /host crictl ps -a | grep etcd || echo "ETCD not found"
        ETCD_ID=$(chroot /host crictl ps -a | grep "etcd " | grep Running | awk '{print $1}')
        if [ ! -z "$ETCD_ID" ]; then
          echo "Stopping etcd container ($ETCD_ID)..."
          chroot /host crictl stop "$ETCD_ID"
          echo "Waiting for etcd to stop..."
          sleep 5
        fi
        echo "Starting netcat on port 2379 to block etcd..."
        # Use a different approach to block the port
        chroot /host /bin/sh -c 'while true; do nc -l -p 2379 -e /bin/false 2>/dev/null || sleep 1; done'
    securityContext:
      privileged: true
    volumeMounts:
    - name: host
      mountPath: /host
  restartPolicy: Never
  volumes:
  - name: host
    hostPath:
      path: /
