apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: mcp-conntrack
  labels:
    machineconfiguration.openshift.io/role: mcp-conntrack
spec:
  machineConfigSelector:
    matchExpressions:
      - {
           key: machineconfiguration.openshift.io/role,
           operator: In,
           values: [worker, mcp-conntrack],
        }
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/mcp-conntrack: "" 
