apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: workshop
  name: 99-network-tools-fix-worker
spec:
  config:
    ignition:
      version: 3.2.0
  osImageURL: "REPLACE_WITH_CORRECT_IMAGE_URL"
