apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: configuration-conntrack
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - name: configuration-conntrack
    data: |
      [main]
      summary=configuration-conntrack
      # override performance addons generated tuned profile
      include=openshift-node-performance-example-performanceprofile
      [video]
      enabled=false
      [sysctl]
      net.netfilter.nf_conntrack_max=8388608
  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: "mcp-conntrack"
    priority: 19
    profile: configuration-conntrack
