apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-mod-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernel-mod-app
  template:
    metadata:
      labels:
        app: kernel-mod-app
    spec:
      containers:
      - name: app
        image: quay.io/jclaret/lab/module-app:latest
