apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc-sysmodule-min
allowPrivilegedContainer: false
allowHostNetwork: false
allowHostPID: false
allowHostIPC: false
allowedCapabilities:
  - SYS_MODULE
seLinuxContext:
  type: RunAsAny
runAsUser:
  type: RunAsAny
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false

