apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-uploader-restore
  namespace: odf-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-uploader-restore
  template:
    metadata:
      labels:
        app: image-uploader-restore
    spec:
      containers:
        - name: web
          #image: quay.io/jclaret/lab/odf-file:latest
          image: registry.offline.lab:5000/lab/odf-file:latest
          env:
            - name: UPLOAD_DIR
              value: /data
            - name: MAX_CONTENT_LENGTH_MB
              value: "10"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rbd-uploader-clonn
---
apiVersion: v1
kind: Service
metadata:
  name: image-uploader-restore
  namespace: odf-clone
spec:
  selector:
    app: image-uploader-restore
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: image-uploader-restore
  namespace: odf-clone
spec:
  to:
    kind: Service
    name: image-uploader-restore
  port:
    targetPort: http
