---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: hello-4
spec:
  imageRepoSecret:
    name: offline-registry
  moduleLoader:
    container:
      modprobe:
        moduleName: hello-4
      kernelMappings:
        - regexp: '5.14.0-427.50.1.el9_4.x86_64'
          containerImage: registry.offline.lab:5000/kmm/mod-container:${KERNEL_FULL_VERSION}
          build:
            baseImageRegistryTLS:
              insecure: false
              insecureSkipTLSVerify: true
            buildArgs:  
              - name: DTK
              # OCP_VERSION=$(oc get clusterversion/version -ojsonpath={.status.desired.version})
              # DRIVER_TOOLKIT_IMAGE=$(oc adm release info quay.io/openshift-release-dev/ocp-release:${OCP_VERSION}-x86_64 --image-for=driver-toolkit)
                value: registry.offline.lab:5000/openshift-release-dev/ocp-v4.0-art-dev@sha256:4341fad46f04641d4f336ffe51c92ce93ea526c829f7afd8a6670c857f2ada17
              - name: KVER
              # KERNEL_VERSION=$(podman run --rm -it $DRIVER_TOOLKIT_IMAGE rpm -q kernel-core --qf '%{VERSION}-%{RELEASE}.%{ARCH}\n' 2>/dev/null)
              # echo "$OCP_VERSION\n$DRIVER_TOOLKIT_IMAGE\n$KERNEL_VERSION\n"
                value: 5.14.0-427.50.1.el9_4.x86_64
            dockerfileConfigMap:  
              name: 23-module-build-dockerfile
          registryTLS:
            insecure: false
            insecureSkipTLSVerify: true
  selector:
    node-role.kubernetes.io/worker: ""
